spring:
    data:
        mongodb:
            host: localhost
            port: 27017
            database: customerdb
            username: root
            password: root
            authentication-database: admin
server:
    port: 8091 
